"""Serves preview audio files generated by Parler-TTS."""

from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from config import settings
from utils.logging_config import get_logger

logger = get_logger("api.previews")

router = APIRouter(prefix="/previews", tags=["previews"])


@router.get("/{date}/{filename}")
async def serve_preview(date: str, filename: str):
    """Serve a preview audio file."""
    for part in (date, filename):
        if ".." in part or "/" in part or "\\" in part:
            raise HTTPException(status_code=400, detail="Invalid path")

    path = (settings.previews_dir / date / filename).resolve()

    if not str(path).startswith(str(settings.previews_dir.resolve())):
        raise HTTPException(status_code=403, detail="Access denied")

    if not path.exists():
        raise HTTPException(status_code=404, detail="Preview audio not found")

    return FileResponse(str(path), media_type="audio/wav", filename=filename)
